version: '2'
services:
  web:
    build: .
    command: php -S 0.0.0.0:8000 -t /code/wordpress/
    ports:
      - "8000:8000"
    depends_on:
      - db
    links: 
      - db
    volumes:
      - .:/code
  db:
    image: orchardup/mysql
    ports:
      - "3306:3306"
    environment:
    - MYSQL_DATABASE=wordpress